// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {imagecore} from '../models';

export function LoadDroppedImage(arg1:string):Promise<imagecore.ImageInfo>;

export function OpenImage():Promise<imagecore.ImageInfo>;

export function PreviewLSB(arg1:imagecore.ExtractRequest):Promise<imagecore.ExtractPreview>;

export function RenderBitPlane(arg1:imagecore.BitPlaneRequest):Promise<string>;

export function SaveBitPlane(arg1:imagecore.BitPlaneRequest):Promise<imagecore.SaveResult>;

export function SaveLSB(arg1:imagecore.ExtractRequest):Promise<imagecore.SaveResult>;
