// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function LoadDroppedImage(arg1) {
  return window['go']['main']['App']['LoadDroppedImage'](arg1);
}

export function OpenImage() {
  return window['go']['main']['App']['OpenImage']();
}

export function PreviewLSB(arg1) {
  return window['go']['main']['App']['PreviewLSB'](arg1);
}

export function RenderBitPlane(arg1) {
  return window['go']['main']['App']['RenderBitPlane'](arg1);
}

export function SaveBitPlane(arg1) {
  return window['go']['main']['App']['SaveBitPlane'](arg1);
}

export function SaveLSB(arg1) {
  return window['go']['main']['App']['SaveLSB'](arg1);
}
